        </div>
        <!-- /container -->
    </div>
    <!-- /main-inner -->
    </div>
    <div id="push"></div>
</div>
<div class="footer">
    <div class="footer-inner">
        <div class="container">
            <div class="row">
                <div class="span12"> &copy; 2013
                    <a href="http://www.egrappler.com/">Bootstrap Responsive Admin Template</a>.
                </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /footer-inner -->
</div>
<!-- /main -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script src="static/js/jquery-1.7.2.min.js"></script>
<script src="static/js/jquery.datetimepicker.js"></script>


<script src="static/js/excanvas.min.js"></script>
<script src="static/js/bootstrap.js"></script>

<script src="static/js/base.js"></script>
<script src="static/js/guidely/guidely.min.js"></script>
        <script src="static/js/scripts.js"></script>
<script>
    /*
     $(function () {

     guidely.add ({
     attachTo: '#target-1'
     , anchor: 'top-left'
     , title: 'Guide Title'
     , text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.'
     });

     guidely.add ({
     attachTo: '#target-2'
     , anchor: 'top-right'
     , title: 'Guide Title'
     , text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.'
     });

     guidely.add ({
     attachTo: '#target-3'
     , anchor: 'middle-middle'
     , title: 'Guide Title'
     , text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.'
     });

     guidely.add ({
     attachTo: '#target-4'
     , anchor: 'top-right'
     , title: 'Guide Title'
     , text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.'
     });

     guidely.init ({ welcome: true, startTrigger: false });


     });
     */

</script>

</body>
</html>
