    <div id="push"></div>
</div>
<div class="footer">
    <div class="footer-inner">
        <div class="container">
            <div class="row">
                <div class="span12"> &copy; 2013 <a href="http://www.egrappler.com/">Bootstrap Responsive Admin Template</a>. </div>
                <!-- /span12 -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /footer-inner -->
</div>
<script src="static/js/jquery-1.7.2.min.js"></script>
<script src="static/js/bootstrap.js"></script>

<script src="static/js/signin.js"></script>

</body>

</html>