<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>AgaMondo</title>
    <base href="<?php echo Config::PATH;?>">
    <link rel="stylesheet" href="static/css/reset.css">
    <link rel="stylesheet" href="static/css/1200gs.css">
    <link rel="stylesheet" href="static/css/style.css">
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script type="text/javascript" src="static/js/tcx.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Audiowide&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Comfortaa&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script type="text/javascript">
        $( document ).ready(function() {
            $('.activity-content-right-more').hide();
            $('#show-hide').click(function() {
                if ($('.activity-content-right-more').is(':hidden')) {
                    $('.activity-content-right-more').fadeIn(1000);
                    $('#show-hide').html('Schowaj');
                }
                else if($('.activity-content-right-more').is(':visible')){
                    $('.activity-content-right-more').fadeOut(1000);
                    $('#show-hide').html('Pokaż więcej');
                }
            });
        });
    </script>
</head>
<body>
    <div id="mainafterlogin">
        <div id="mainafterlogin-heading" class="heading">
            <ul class="user-nav">
                <li>
                    <h3>Witaj, <?php echo $_SESSION['login']?></h3>
                </li>
                <li id="avatar-li">
                    <a id="avatar-a" href="#">
                        <div id="avatar">
                            <img src="static/img/avatar.jpg" alt="avatar">
                        </div>
                    </a>
                    <ul>
                        <li>
                            <a href="training/add/"> <div>Dodaj trening</div></a>
                        </li>
                        <li>
                            <a href="auth/edit/"><div>Edytuj profil</div></a>
                        </li>
                        <li>
                            <a href="auth/password/"><div>Zmień hasło</div></a>
                        </li>
                        <li>
                            <a href="<?php /*echo Config::PATH; */?>main/logout"><div>Wyloguj</div></a>
                        </li>
                    </ul>
                </li>
            </ul>
            <a class="logo" href="/">
                <h1><span>AGA</span>MONDO</h1>
            </a>
            <ul class="global-nav">
                <li>
                    <a href="training/trainings/">Treningi</a>
                </li>
            </ul>
        </div>
    </div>