<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>AgaMondo</title>
    <base href="<?php echo Config::PATH;?>">
    <link rel="stylesheet" href="static/css/reset.css">
    <link rel="stylesheet" href="static/css/1200gs.css">
    <link rel="stylesheet" href="static/css/style.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script type="text/javascript" src="static/js/main.js"></script>

    <link href='http://fonts.googleapis.com/css?family=Audiowide&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="heading">
        <div class="heading-button">
            <?php
            if ($this->action == 'login') {
                ?>
                <a href="">
                    <button>Rejestracja</button>
                </a>
            <?php
            } else {
                ?>
                <a href="auth/login/">
                    <button>Zaloguj się</button>
                </a>
            <?php
            }
            ?>
        </div>

        <ul class="social">
            <li>
                <a href="www.facebook.com">
                    <img src="static/img/twitter_small.png">
                </a>
            </li>
            <li>
                <a href="www.twitter.com">
                    <img src="static/img/facebook_small.png"/>
                </a>
            </li>
        </ul>
        <a class="logo" href="/">
            <h1><span>AGA</span>MONDO</h1>
        </a>
    </div>


