<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml">
<head >
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <title>AgaMondo</title>
    <link rel="stylesheet" href="static/css/reset.css">
    <link rel="stylesheet" href="static/css/1200gs.css">
    <link rel="stylesheet" href="static/css/style.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
    <script type="text/javascript" src="static/js/main.js"></script>
    <base href="http://localhost/project/agamondo/">
    <link href='http://fonts.googleapis.com/css?family=Audiowide&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<body>
    <div class="heading">
        <div class="heading-button">
            <a href="">
                <button>Zaloguj się</button>
            </a>
        </div>

        <ul class="social">
            <li>
                <a href="www.facebook.com">
                    <img src="static/img/twitter_small.png">
                </a>
            </li>
            <li>
                <a href="www.twitter.com">
                    <img src="static/img/facebook_small.png"/>
                </a>
            </li>
        </ul>
        <a class="logo" href="/">
            <h1><span>AGA</span>MONDO</h1>
        </a>
    </div>


