<script language="javascript" type="text/javascript" src="static/js/jquery.flot.js"></script>
<script language="javascript" type="text/javascript" src="static/js/jquery.flot.crosshair.js"></script>
<script type="text/javascript" src="static/js/graphs.js"></script>
<script type="text/javascript">
    $( document ).ready(function() {
        var xmls = [];
        <?php
            /*$ResultsReversed = array_reverse($Results);*/
            /*foreach($ResultsReversed as &$training){*/

                $Results = preg_replace('/\s+/', '', $Results);
                echo 'xmls.push(\''.$Results['xml'].'\');';
            /*}*/
        ?>
        $('.map_canvas').each(function() {
            displayMap($(this).attr('id'));
        });


        function displayMap(idMapy) {
            xml = xmls.pop();
            var map = new google.maps.Map(document.getElementById(idMapy), {
                mapTypeId: google.maps.MapTypeId.TERRAIN
            });

            var points = [];
            var end_myLatLng=0;
            var start_myLatLng=0;
            var bounds = new google.maps.LatLngBounds ();
            $(xml).find("Position").each(function(i) {
                var lat=$(this).find("LatitudeDegrees").text();
                var lon = $(this).find("LongitudeDegrees").text();
                if(i==0)
                    start_myLatLng = new google.maps.LatLng(lat, lon);
                var p = new google.maps.LatLng(lat, lon);
                points.push(p);
                bounds.extend(p);
                end_myLatLng = new google.maps.LatLng(lat, lon);
            });

            var marker = new google.maps.Marker({
                position: start_myLatLng,
                map: map,
                title: 'Start',
                icon: 'static/img/start.png'
            });
            var marker2 = new google.maps.Marker({
                position: end_myLatLng,
                map: map,
                title: 'Meta',
                icon: 'static/img/finish.png'
            });


            var poly = new google.maps.Polyline({
                path: points,
                strokeColor: "#EF3038",
                strokeOpacity: .7,
                strokeWeight: 4
            });

            poly.setMap(map);
            map.fitBounds(bounds);
            getPoint();
        }

    });
</script>

<div class="activity">
    <div class="activity-header">

        <h3>Tytuł: <?php echo $Results['title'];?> - Rodzaj aktywności: <?php echo $Results['name'];?></h3>
        <a href="training/delete/<?php echo $Results['id'];?>
        " onclick="return confirm('Czy na pewno chcesz usunąć trening <?php echo $Results['title'];?>?')">
            <img id="delete"src="static/img/delete.png"/>
        </a>
    </div>
    <div class="activity-content">
        <div class="activity-content-left">
            <div class="avatar-activity">
                <img src="static/img/avatar.jpg" alt="avatar">
            </div>
            <h4>Data Treningu: <?php echo substr($Results['date'], 0, 10);
                /*echo $date;*/?></h4>
            <a href=""><?php echo $_SESSION['login']; ?></a>
            <h5>Opis treningu:</h5>
            <h6><?php echo $Results['description']; ?></h6>
        </div>
        <div class="activity-content-right">
            <div class="activity-content-right-distance">
                <h3><?php

                    if($Results['distance'] < 1)
                        echo htmlspecialchars(round($Results['distance']*1000, 1, PHP_ROUND_HALF_UP), ENT_QUOTES, 'UTF-8').' m';
                    else
                        echo htmlspecialchars($Results['distance'], ENT_QUOTES, 'UTF-8').' km';
                    ?></h3>
                <h6>Dystans</h6>
            </div>
            <div class="activity-content-right-time">
                <h3><?php echo $Results['time']; ?></h3>
                <h6>Czas</h6>
            </div>
            <div class="activity-content-right-calories">
                <h3><?php echo $Results['calories']; ?></h3>
                <h6>Kalorie</h6>
            </div>
            <div class="activity-content-right-button">
                <button id="show-hide">Pokaż więcej</button>
            </div>
            <div class="activity-content-right-more">
                <div class="activity-content-right-more-label">
                    <h3>Prędkość średnia:</h3>
                    <h3>Prędkość maksymalna:</h3>
                    <h3>Przewyższenie:</h3>
                    <h3>Wysokość maksymalna:</h3>
                </div>
                <div class="activity-content-right-more-speed">
                    <h4><?php
                        list($hour, $minute, $second) = preg_split('/[: -]/', $Results['time']);
                        $time =$hour + round(($minute/60),2);
                        $Average =  round((($Results['distance'])/$time),1);
                        echo $Average;?> km/h</h4>

                    <h4 id="max_speed"></h4>
                    <h4 id="altitude"></h4>
                    <h4 id="max_altitude"></h4>
                </div>
            </div>
        </div>
    </div>

</div>
<div id="google-map-<?php echo 1;?>" class="map_canvas" >
</div>
<div class="graph">
    <div id="placeholder" class="graph-placeholder"></div>
</div>