<script type="text/javascript">
    $( document ).ready(function() {
        var xmls = [];
        <?php
            $ResultsReversed = array_reverse($Results);
            foreach($ResultsReversed as &$training){
                $training = preg_replace('/\s+/', '', $training);
                echo 'xmls.push(\''.$training['xml'].'\');';
            }
        ?>

        $('.google-map').each(function() {
            displayMap($(this).attr('id'));
        });


        function displayMap(idMapy) {
            xml = xmls.pop();
            var map = new google.maps.Map(document.getElementById(idMapy), {
                mapTypeId: google.maps.MapTypeId.TERRAIN
            });

            var points = [];
            var bounds = new google.maps.LatLngBounds ();
            $(xml).find("Position").each(function() {
                var lat=$(this).find("LatitudeDegrees").text();
                var lon = $(this).find("LongitudeDegrees").text();
                var p = new google.maps.LatLng(lat, lon);
                points.push(p);
                bounds.extend(p);
            });

            var poly = new google.maps.Polyline({
                path: points,
                strokeColor: "#EF3038",
                strokeOpacity: .7,
                strokeWeight: 4
            });

            poly.setMap(map);
            map.fitBounds(bounds);

        }
    });
</script>
<div id="mainafterlogin-content">
    <h3 id="mainafterlogin-training-margin">Twoje ostatnie aktywności:</h3>

    <?php
        if(empty($Results)){
//
//        require 'application/views/training/no_training.phtml';
//
    ?>
        Brak treningów
    <?php
        }
        else{
            $i = 1;
            foreach($Results as &$training){
        ?>
                <div class="mainafterlogin-training">
                    <div class="mainafterlogin-training-left">
                        <div class="avatar-training">
                            <img src="static/img/avatar.jpg" alt="avatar">
                        </div>
                    </div>
                    <div class="mainafterlogin-training-right">
                        <div class="mainafterlogin-training-right-link">
                            <a href="@"><?php echo $training['title']; ?></a>
                        </div>
                        <div class="mainafterlogin-training-right-name">
                            <a href="@"><?php echo $training['name']; ?></a>
                        </div>
                        <div class="mainafterlogin-training-right-stat">
                            <h6>Dystans: <?php echo htmlspecialchars($training['distance'], ENT_QUOTES, 'UTF-8');?> km
                            </h6>
                            <h6>Czas: <?php echo htmlspecialchars($training['time'], ENT_QUOTES, 'UTF-8'); ?></h6>
                        </div>
                        <div id="google-map-<?php echo $i++;?>" class="google-map" style="width: 40%; height: 80%;">
                        </div>
                    </div>
                </div>

            <?php
            }
        }
    ?>

</div>
</div>