<script type="text/javascript">
    $( document ).ready(function() {
        var xmls = [];
        <?php
            foreach($Results as &$training){
                $training = preg_replace('/\s+/', '', $training);
                echo 'xmls.push(\''.$training['xml'].'\');';
            }
        ?>
        initialize('map','<?php
                    echo $Results[2]['xml'];
                    ?> ');
        initialize('map2', 'static/trainings-xml.bin');
        initialize('map3', 'static/trasa.tcx');
    });
</script>
<div id="mainafterlogin-content">
    <h3>Twoje ostatnie aktywności:</h3>

    <?php
        if(empty($Results)){
//
//        require 'application/views/training/no_training.phtml';
//
    ?>
        Brak treningów
    <?php
        }
        else{
            foreach($Results as &$training){
        ?>
                <div id="mainafterlogin-training-margin" class="mainafterlogin-training">
                    <div class="mainafterlogin-training-left">
                        <div class="avatar-training">
                            <img src="static/img/avatar.jpg" alt="avatar">
                        </div>
                    </div>
                    <div class="mainafterlogin-training-right">
                        <div class="mainafterlogin-training-right-link">
                            <a href="@"><?php echo $training['title']; ?></a>
                        </div>
                        <div class="mainafterlogin-training-right-name">
                            <a href="@"><?php echo $training['name']; ?></a>
                        </div>
                        <div class="mainafterlogin-training-right-stat">
                            <h6>Dystans: <?php echo htmlspecialchars($training['distance'], ENT_QUOTES, 'UTF-8');?> km
                            </h6>
                            <h6>Czas: <?php echo htmlspecialchars($training['time'], ENT_QUOTES, 'UTF-8'); ?></h6>
                        </div>
                        <div id="map" style="width: 40%; height: 80%;">
                        </div>
                    </div>
                </div>

            <?php
            }
        }
    ?>

</div>
</div>