<div class="summation">
    <h3>Miesięczne podsumowanie profilu:</h3>
    <div class="summation-button">
        <h4>Wybierz miesiąc</h4>
        <button>Styczeń</button>
        <button>Luty</button>
        <button>Marzec</button>
    </div>
    <div>
        <h4>Styczeń</h4>
        <p>Dystans całkowity: <?php echo $Results[0]['distance'];?></p>
        <p>Czas całkowity: <?php echo $Results[0]['sum_time'];?></p>
    </div>
</div>