<div id="signup">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/editUser/" method="post">
                <div class = "form-heading" >
                    <h3>Edycja konta</h3>
                </div>
                <input type="text" placeholder="Nazwa użytkownika" id="username" name="login" value="<?php echo $user['login'];?>">
                <input type="text" placeholder="Imię i Nazwisko" id="name" name="name" value="<?php echo $user['name'];?>">
                <input type="text" placeholder="Twój email" id="email" name="email" value="<?php echo $user['email'];?>">
                <input type="text" placeholder="Wzrost" id="weight" name="weight" value="<?php echo $user['weight'];?>">
                <input type="text" placeholder="Waga" id="height" name="height" value="<?php echo $user['height'];?>">
                <input type="hidden" name="id" value="<?php echo $user['id']; ?>" />
                <div class="form-footer">
                    <button id="form-footer-button" type="submit">Edytuj</button>
                </div>
            </form>
        </div>
    </div>
</div>
