<div id="signup">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/editUser/" method="post">
                <div class = "form-heading" >
                    <h3>Edycja konta</h3>
                </div>
                <?php
                if(isset($resp['type'])){
                    echo $resp['text'];
                }
                ?>
                <label>Nazwa użytkownika:</label>
                <input type="text" placeholder="Nazwa użytkownika" id="username" name="login" value="<?php echo $user['login'];?>">

                <label>Imię i nazwisko:</label>
                <input type="text" placeholder="Imię i nazwisko" id="name" name="name" value="<?php echo $user['name'];?>">

                <label>Twój email:</label>
                <input type="text" placeholder="Twój email" id="email" name="email" value="<?php echo $user['email'];?>">

                <label>Waga (kg):</label>
                <input type="text" placeholder="Waga" id="weight" name="weight" value="<?php echo $user['weight'];?>">

                <label>Wzrost (cm):</label>
                <input type="text" placeholder="Wzrost" id="height" name="height" value="<?php echo $user['height'];?>">

                <div class="form-footer">
                    <button id="form-footer-button" type="submit">Zapisz</button>
                </div>
            </form>
        </div>
    </div>
</div>