<div id="signup">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/edit/" method="post">
                <div class = "form-heading" >
                    <h3>Edycja konta</h3>
                </div>
                <input type="text" placeholder="Nazwa użytkownika" id="username" name="login" value="<?php echo $user['login'];?>">
                <input type="text" placeholder="Twój email" id="email" name="email" value="<?php echo $user['email'];?>">
                <div class="form-footer">
                    <button id="form-footer-button">Zarejestruj</button>
                </div>
            </form>
        </div>
    </div>
</div>
<h3>Edit a song</h3>
<form action="<?php echo URL; ?>songs/updatesong" method="POST">
    <label>Artist</label>
    <input autofocus type="text" name="artist" value="<?php echo htmlspecialchars($song->artist, ENT_QUOTES, 'UTF-8'); ?>" required />
    <label>Track</label>
    <input type="text" name="track" value="<?php echo htmlspecialchars($song->track, ENT_QUOTES, 'UTF-8'); ?>" required />
    <label>Link</label>
    <input type="text" name="link" value="<?php echo htmlspecialchars($song->link, ENT_QUOTES, 'UTF-8'); ?>" />
    <input type="hidden" name="song_id" value="<?php echo htmlspecialchars($song->id, ENT_QUOTES, 'UTF-8'); ?>" />
    <input type="submit" name="submit_update_user" value="Update" />
</form>