<div class="account-container">

    <div class="content clearfix">

        <form action="auth/sendrecoverpasswordemail/" method="post">

            <h1>Przypomnnij hasło</h1>

            <div class="login-fields">
                <?php
                    if($resp['type'] === 0){
                        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
                    }
                    elseif($resp['type'] === 1){
                        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
                    }
                ?>
                <p>Na Twój adres e-mail zostaną wysłane dalsze instrukcje.</p>
                <div class="field">
                    <label for="username">E-mail:</label>
                    <input type="text" name="email" value="" placeholder="E-mail" class="login username-field" />
                </div> <!-- /field -->

            </div> <!-- /login-fields -->

            <div class="login-actions">

                <button class="button btn btn-success btn-large">Dalej</button>

            </div> <!-- .actions -->



        </form>

    </div> <!-- /content -->

</div> <!-- /account-container -->

