<div id="login">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/sendrecoverpasswordemail/" method="post">
                <div class = "form-heading" >
                    <h3>Zaloguj się</h3>
                </div>
                <?php
                    if($resp['type'] === 0){
                        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
                    }
                    elseif($resp['type'] === 1){
                        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
                    }
                ?>
                <p>Na Twój adres e-mail zostaną wysłane dalsze instrukcje.</p>
                <label>Adres e-mail:</label>
                <input id="username" type="text" name="email">

                <div class="form-footer">
                    <button id="form-footer-button">Zaloguj się</button>
                </div>
            </form>
        </div>
    </div>
</div>
