<div id="login">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/sendrecoverpasswordemail/" method="post">
                <div class = "form-heading" >
                    <h3>Przypomnienie</h3>
                </div>
                <?php
                    /*if($resp['type'] === 0){
                        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
                    }
                    elseif($resp['type'] === 1){
                        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
                    }*/
                if($resp['type'] === 0){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                elseif($resp['type'] === 1){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                ?>
                <div class="validation-summary-errors">
                    <p>Na Twój adres e-mail zostaną wysłane dalsze instrukcje.</p>
                </div>
                <label>Adres e-mail:</label>
                <input id="username" type="text" name="email">

                <div class="form-footer">
                    <button id="form-footer-button">Wyślij</button>
                </div>
            </form>
        </div>
    </div>
</div>
