<div id="login">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/login/" method="post">
                <div class = "form-heading" >
                    <a href="">
                        <h3>Zaloguj się</h3>
                    </a>
                </div>
                <label for="username">Nazwa użytkownika:</label>
                <input type="text" id="username" name="login">
                <label for="password">Hasło:</label>
                <input type="password" id="password" name="password" autocomplete="off">
                <input type="checkbox" id="checkbox">
                <label class="check" for="checkbox">Zapamiętaj mnie</label>
                <div class="form-footer">
                    <button id="form-footer-button">Zaloguj się</button>
                </div>
            </form>
        </div>
    </div>
</div>

