<div id="login">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/login/" method="post">
                <div class = "form-heading" >
                    <h3>Zaloguj się</h3>
                </div>
                <?php
                if($resp['type'] === 0){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                elseif($resp['type'] === 1){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                ?>
                <label for="username">Nazwa użytkownika:</label>
                <input type="text" id="username" name="login">
                <label for="password">Hasło:</label>
                <input type="password" id="password" name="password" autocomplete="off">

                <a href="auth/forgetpassword/" class="check">Zapomniałem hasła</a>
                <div class="form-footer">
                    <button id="form-footer-button">Zaloguj się</button>
                </div>
            </form>
        </div>
    </div>
</div>

