<div id="signup">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/changepassword/" method="post">
                <div class = "form-heading" >
                    <h3>Zmiana hasła</h3>
                </div>
                <?php
                if(isset($resp['type'])){
                    echo $resp['text'];
                }
                ?>
                <label>Stare hasło:</label>
                <input type="password" placeholder="Stare hasło" id="username" name="old">

                <label>Nowe hasło:</label>
                <input type="password" placeholder="Nowe hasło" id="username" name="password1">

                <label>Powtórz nowe hasło:</label>
                <input type="password" placeholder="Powtórz nowe hasło" id="username" name="password2">


                <div class="form-footer">
                    <button id="form-footer-button" type="submit">Zapisz</button>
                </div>
            </form>
        </div>
    </div>
</div>