<div id="signup">
    <div class="centered-vertically">
        <div class="form-container">
            <form action="auth/register/" method="post">
                <div class = "form-heading" >
                        <h3>Rejestracja</h3>
                </div>
                <?php
                if($resp['type'] === 0){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                elseif($resp['type'] === 1){
                    echo '<div class="validation-summary-errors"><p>'.$resp['text'].'</p></div>';
                }
                ?>
                <label>Nazwa użytkownika:</label>
                <input type="text" placeholder="Nazwa użytkownika" id="username" name="login" autocomplete="off" value="<?php echo $value['login'];?>">

                <label>Twój e-mail:</label>
                <input type="text" placeholder="Twój email" id="email" name="email" autocomplete="off" value="<?php echo $value['email'];?>">
                <label>Hasło:</label>
                <input type="password" placeholder="Hasło" id="password" name="password1" autocomplete="off">

                <label>Powtórz hasło:</label>
                <input type="password" placeholder="Powtórz Hasło" id="password2" name="password2" autocomplete="off">
                <div class="form-footer">
                    <button id="form-footer-button">Zarejestruj</button>
                </div>
            </form>
        </div>
    </div>
</div>