
<div class="row">
    <div class="span6">
        <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
                <h3>Dodaj użytkownika</h3>
            </div>

            <!-- /widget-header -->
            <div class="widget-content" style="padding: 20px;">
                <?php
                    if($resp['type'] === 0){
                        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
                    }
                    elseif($resp['type'] === 1){
                        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
                    }
                ?>

                <form action="main/addinguser/" method="post">
                    <input type="hidden" name="csrf_token" value="<?php echo $this->NoCSRFToken;?>" />
                    <div class="settings-item">
                        <label>Login</label>
                        <input type="text" name="login" value="<?php echo $inputs['login'];?>">
                    </div>
                    <div class="settings-item">
                        <label>E-mail</label>
                        <input type="text" name="email" value="<?php echo $inputs['email'];?>">
                    </div>
                    <div class="settings-item">
                        <label>Hasło</label>
                        <input type="password" name="password1">
                    </div>
                    <div class="settings-item">
                        <label>Powtórz Hasło</label>
                        <input type="password" name="password2">
                    </div>
                    <div class="settings-item">
                        <label>Imię i nazwisko</label>
                        <input type="text" name="name" value="<?php echo $inputs['name'];?>">
                    </div>

                    <button class="btn btn-primary" style="float: right">Zapisz</button>
                </form>
            </div>
            <!-- /widget-content -->
        </div>
        <!-- /widget -->
        <!-- /widget -->
    </div>

    <div class="span6">
        <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
                <h3>Użytkownicy</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th> Login</th>
                        <th> Adres e-mail</th>
                        <th> Imię i nazwisko</th>
                        <th> Data dodania</th>
                        <th class="td-actions">Zarządzanie </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($Users as $row) { ?>
                        <tr id="answer-<?php echo $row['id']; ?>">
                            <td> <?php echo $row['login']?></td>
                            <td> <?php echo $row['email']; ?></td>
                            <td> <?php echo $row['name']; ?></td>
                            <td> <?php echo $row['date_register']; ?></td>
                            <td class="td-actions">
                                <form action="main/deleteuser/" method="post" style="margin: 0">
                                    <input type="hidden" name="csrf_token" value="<?php echo $this->NoCSRFToken;?>" />
                                    <input type="hidden" name="id" value="<?php echo $row['id']; ?>" >
                                    <button onclick="return confirm('Czy na pewno chcesz usunąć użytkownika <?php echo $row['login']?>?')" class="btn btn-danger btn-small"><i class="btn-icon-only icon-remove"> </i></button>
                                </form>
                            </td>
                        </tr>
                        <tr id="answer-text-<?php echo $row['id']; ?>" class="display-none">
                            <td colspan="6" class="grey-bg"><?php echo $row['answer']; ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
            <!-- /widget-content -->
        </div>
    </div>

    <!-- /span6 -->
</div>
<!-- /row -->