<div id="mainafterlogin-content">
    <h3>Twoje ostatnie aktywności:</h3>
    <div  id="mainafterlogin-training-margin" class="mainafterlogin-training">
        <div class="mainafterlogin-training-left">
            <div class="avatar-training">
                <img src="static/img/avatar.jpg" alt="avatar">
            </div>
        </div>
        <div class="mainafterlogin-training-right">
            <div class="mainafterlogin-training-right-link">
                <a href="@">11/30/2014 Ozorków, Lodzkie, Poland</a>
            </div>
            <div class="mainafterlogin-training-right-name">
                <a href="@">Kamil Wójt</a>
            </div>
            <div class="mainafterlogin-training-right-stat">
                <h6>Dystans: <?php
                    var_dump($Results);
                    if (isset($Results['time'])) echo htmlspecialchars($Results['time'], ENT_QUOTES, 'UTF-8'); ?></h6>
                <h6>Tempo: 5:13/km</h6>
            </div>
            <div id="map" style="width: 40%; height: 80%;">
            </div>
        </div>
    </div>
    <div class="mainafterlogin-training">
        <div class="mainafterlogin-training-left">
            <div class="avatar-training">
                <img src="static/img/avatar.jpg" alt="avatar">
            </div>
        </div>
        <div class="mainafterlogin-training-right">
            <div class="mainafterlogin-training-right-link">
                <a href="@">11/30/2014 Ozorków, Lodzkie, Poland</a>
            </div>
            <div class="mainafterlogin-training-right-name">
                <a href="@">Kamil Wójt</a>
            </div>
            <div class="mainafterlogin-training-right-stat">
                <h6>Dystans: 9.6km </h6>
                <h6>Tempo: 5:13/km</h6>
            </div>
            <div id="map2" style="width: 40%; height: 80%;">
            </div>
        </div>
    </div>
    <div class="mainafterlogin-training">
        <div class="mainafterlogin-training-left">
            <div class="avatar-training">
                <img src="static/img/avatar.jpg" alt="avatar">
            </div>
        </div>
        <div class="mainafterlogin-training-right">
            <div class="mainafterlogin-training-right-link">
                <a href="@">11/30/2014 Ozorków, Lodzkie, Poland</a>
            </div>
            <div class="mainafterlogin-training-right-name">
                <a href="@">Kamil Wójt</a>
            </div>
            <div class="mainafterlogin-training-right-stat">
                <h6>Dystans: 9.6km </h6>
                <h6>Tempo: 5:13/km</h6>
            </div>
            <div id="map3" style="width: 40%; height: 80%;">
            </div>
        </div>
    </div>
</div>
</div>