<div class="row">
    <div class="span6">
        <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
                <h3>Zgłoszenia</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">
                <div class="stat-content">
                    <div class="count-answers">
                        <span style="margin-right:20px;">Liczba zgłoszeń: <strong class="large-font"><?php echo $countAnswers; ?></strong> </span>
                        <span style="margin-right:20px;">Zgłoszeń dzisiaj: <strong class="large-font"> <?php echo $answersToday; ?></strong></span>
                        <span>Zgłoszeń wczoraj: <strong class="large-font"> <?php echo $answersYesterday; ?></strong></span>
                    </div>
                    <div class="paggination-form">
                        <form action="<?php echo Config::PATH; ?>" method="post" name="paggination-form" id="paggination-form">
                            <div class="paggination-form-input">
                                <label>Rekordów na stronie: </label>
                                <select name="max">
                                    <option value="20" <?php if($_SESSION['max'] == 20) echo 'selected'; ?>>20</option>
                                    <option value="50" <?php if($_SESSION['max'] == 50) echo 'selected'; ?>>50</option>
                                    <option value="100" <?php if($_SESSION['max'] == 100) echo 'selected'; ?>>100</option>
                                    <option value="200" <?php if($_SESSION['max'] == 200) echo 'selected'; ?>>200</option>
                                </select>
                                <input type="hidden" name="from" value="<?php echo $from; ?>">
                                <button class="btn btn-primary">Wyświetl</button>
                            </div>
                        </form>
                        <div class="paggination-form-input">
                            <input type="hidden" name="from" value="<?php echo $from; ?>">
                            <a href="<?php echo Config::PATH.'main/index/'; echo $page-1; ?>" <?php if($page == 1) echo 'class="disabled"'; ?>>
                                <button class="btn" style="float: left; margin-right: 10px;"  <?php if($page == 1) echo 'disabled'; ?>>Poprzednia strona</button>
                            </a>
                            <ul class="paggination-list">
                                <?php  for($i = 0; $i <= $maxPages; $i++){
                                    if((($i+1)*$_SESSION['max']-$countAnswers) >= $_SESSION['max'])
                                        break;
                                ?>
                                <li <?php if($page == $i+1) echo 'class="current-li"'; ?>><a href="<?php echo Config::PATH.'main/index/'; echo $i+1; ?>"><?php echo $i+1; ?></a></li>
                                <?php } ?>
                            </ul>
                            <a href="<?php echo Config::PATH.'main/index/'; echo $page+1; ?>" <?php if($page > $maxPages) echo 'class="disabled"'; ?>>
                                <button class="btn" style="margin-left: 10px;" <?php if($page >= $maxPages) echo 'disabled'; ?>>Następna strona </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /widget-content -->
        </div>
        <!-- /widget -->

        <!-- /widget -->
    </div>

<div class="span6"><?php
    if($resp['type'] === 0){
        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
    }
    elseif($resp['type'] === 1){
        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
    }
    ?>
    <div class="widget widget-table action-table">
        <div class="widget-header">
            <i class="icon-th-list"></i>
            <h3>List zgłoszeń</h3>
            <a href="ajax/downloadExcel2/" style="display: block; float: right;">
                <button class="btn" style="margin-right: 10px;">Eksportuj do Excel</button>
            </a>
        </div>
        <!-- /widget-header -->
        <div class="widget-content">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th> Imię i nazwisko (IP) </th>
                    <th> Adres e-mail</th>
                    <th> Numer telefonu</th>
                    <th> Odpowiedź</th>
                    <th> Data dodania</th>
                    <th class="td-actions">Zarządzanie </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($result as $row) { ?>
                <tr id="answer-<?php echo $row['id']; ?>">
                    <td> <?php echo $row['name']; ?> <div class="ip-small">(IP: <?php echo $row['ip']; ?>)</div> </td>
                    <td> <?php echo $row['email']; ?>  </td>
                    <td> <?php if($row['phone'] != null && $row['phone'] != ' ') echo $row[phone]; else echo '<div class="row-null">nie podano</div>'; ?>  </td>
                    <td class="expand"> rozwiń</td>
                    <td> <?php echo $row['date']; ?></td>
                    <td class="td-actions">
                        <form action="main/deleteanswer/<?php echo $page; ?>/" method="post" style="margin: 0">
                            <input type="hidden" name="csrf_token" value="<?php echo $this->NoCSRFToken;?>" />
                            <input type="hidden" name="id" value="<?php echo $row['id']; ?>" >
                            <button onclick="return confirm('Czy na pewno chcesz usunąć tą odpowiedź?')" class="btn btn-danger btn-small"><i class="btn-icon-only icon-remove"> </i></button>
                        </form>
                    </td>
                </tr>
                <tr id="answer-text-<?php echo $row['id']; ?>" class="display-none">
                    <td colspan="6" class="grey-bg"><?php echo nl2br($row['answer']); ?></td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
            <div class="paggination-form-input" style="margin:20px;">
                <input type="hidden" name="from" value="<?php echo $from; ?>">
                <a href="<?php echo Config::PATH.'main/index/'; echo $page-1; ?>" <?php if($page == 1) echo 'class="disabled"'; ?>>
                    <button class="btn" style="float: left; margin-right: 10px;"  <?php if($page == 1) echo 'disabled'; ?>>Poprzednia strona</button>
                </a>
                <ul class="paggination-list">
                    <?php  for($i = 0; $i <= $maxPages; $i++){
                        if((($i+1)*$_SESSION['max']-$countAnswers) >= $_SESSION['max'])
                            break;
                        ?>
                        <li <?php if($page == $i+1) echo 'class="current-li"'; ?>><a href="<?php echo Config::PATH.'main/index/'; echo $i+1; ?>"><?php echo $i+1; ?></a></li>
                    <?php } ?>
                </ul>
                <a href="<?php echo Config::PATH.'main/index/'; echo $page+1; ?>" <?php if($page > $maxPages) echo 'class="disabled"'; ?>'>
                <button class="btn" style="margin-left: 10px;" <?php if($page >= $maxPages) echo 'disabled'; ?>>Następna strona </button>
                </a>
            </div>
        </div>
        <!-- /widget-content -->
    </div>
    <!-- /widget -->

    <!-- /widget -->
</div>
<!-- /span6 -->
</div>
<!-- /row -->