<div class="container">
    <section id="mainpage1" class="active">
        <div id="mainpage1-content">
            <h2>TRENUJ - BAW SIĘ - LEVELUJ</h2>
            <h3>Z <span>AGA</span>MONDO</h3>
            <a href="@Url.Action("Register", "Account" )">
            <button id="mainpage1-button">Zarejestruj się</button>
            </a>
        </div>
    </section>
    <section id="mainpage2">
        <div id="mainpage2-heading">
            <h2>TO TAKIE PROSTE...</h2>
        </div>
        <div class="centered-vertically">
            <div id="mainpage2-content">
                <img src="Content/themes/base/images/21.png" alt="smartfon" />
                <div class="arrow animated bounce"><img id="arrow-margin" src="Content/themes/base/images/arrow.png" alt="arrow" /></div>
                <img src="Content/themes/base/images/22.png" alt="sports" />
                <div class="arrow animated bounce"><img id="arrow-margin" src="Content/themes/base/images/arrow.png" alt="arrow" /></div>
                <img src="Content/themes/base/images/23.png" alt="laptops" />
                <ul>
                    <li>
                        <h3>Zainstaluj Agamondo</h3>
                    </li>
                    <li>
                        <h3>Podejmij wyzwanie</h3>
                    </li>
                    <li>
                        <h3>Analizuj aktywność</h3>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section id="mainpage3"><h2>Third</h2></section>
    <section id="mainpage4"><h2>Fourth</h2></section>
    <section id="mainpage5"><h2>Fifth</h2></section>
</div>

<div id="slide-nav">
    <ul>
        <li class="active"><a href="#mainpage1"></a></li>
        <li><a href="#mainpage2"></a></li>
        <li><a href="#mainpage3"></a></li>
        <li><a href="#mainpage4"></a></li>
        <li><a href="#mainpage5"></a></li>
    </ul>
</div>