<div class="container">
    <section id="mainpage1" class="active">
        <div id="mainpage1-content">
            <h2>TRENUJ - BAW SIĘ - LEVELUJ</h2>
            <h3>Z <span>AGA</span>MONDO</h3>
            <a href="auth/register/">
                <button id="mainpage1-button">Zarejestruj się</button>
            </a>
        </div>
    </section>
    <section id="mainpage2">
        <div id="mainpage2-heading">
            <h2>TO TAKIE PROSTE...</h2>
        </div>
        <div class="centered-vertically">
            <div id="mainpage2-content">
                <img src="static/img/21.png" alt="smartfon" />
                <div class="arrow animated bounce"><img id="arrow-margin" src="static/img/arrow.png" alt="arrow" /></div>
                <img src="static/img/22.png" alt="sports" />
                <div class="arrow animated bounce"><img id="arrow-margin" src="static/img/arrow.png" alt="arrow" /></div>
                <img src="static/img/23.png" alt="laptops" />
                <ul>
                    <li>
                        <h3>Zainstaluj Agamondo</h3>
                    </li>
                    <li>
                        <h3>Podejmij wyzwanie</h3>
                    </li>
                    <li>
                        <h3>Analizuj aktywność</h3>
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <section id="mainpage3">
        <h2>Co w Agamondo</h2>
        <div class="mainpage3-center">
            <div class="mainpage3-col">
                <div class="mainpage3-col-effect">
                    <div class="mainpage3-col-effect-img">
                        <div class="mainpage3-col-effect-img-inside">
                            <div class="mainpage3-col-effect-img-inside-img" style="background:url(static/img/map.png) no-repeat center center;">
                            </div>
                        </div>
                    </div>
                    <div class="mainpage3-col-effect-head">
                        Mapy Google
                    </div>
                    <div class="mainpage3-col-effect-text">
                        <p>Dzięki aplikacji Agamondo każdy swój trening będziesz mógł analizować na mapach Google.
                        Obsługiwany format pliku .tcx zapewnia, że każdy Twój ruch zostanie uwidoczniony na mapie oraz
                        zostaną pobrane dokładne informację o Twoim treningu.</p>
                    </div>
                </div>
            </div>

            <div class="mainpage3-col">
                <div class="mainpage3-col-effect">
                    <div class="mainpage3-col-effect-img">
                        <div class="mainpage3-col-effect-img-inside">
                            <div class="mainpage3-col-effect-img-inside-img" style="background:url(static/img/charts2.png) no-repeat center center;">
                            </div>
                        </div>
                    </div>
                    <div class="mainpage3-col-effect-head">
                        Wykresy treningów
                    </div>
                    <div class="mainpage3-col-effect-text">
                        <p>Piękne i efektowne wykresy, na których zostanie przedstawiony Twój trening już teraz w Agamondo.
                        Dokładne wartości prędkości i wysokości w każdej sekundzie Twojego treningu.</p>
                    </div>
                </div>
            </div>
            <div class="mainpage3-col">
                <div class="mainpage3-col-effect">
                    <div class="mainpage3-col-effect-img">
                        <div class="mainpage3-col-effect-img-inside">
                            <div class="mainpage3-col-effect-img-inside-img" style="background:url(static/img/charts.png) no-repeat center center;">
                            </div>
                        </div>
                    </div>
                    <div class="mainpage3-col-effect-head">
                        Rozbudowana analiza treningu
                    </div>
                    <div class="mainpage3-col-effect-text">
                        <p>Dokładne informacje o Twoim treningu takie jak: całkowity dystans, spalone kalorie, pokonane
                        przewyższenie, średnia prędkość i wiele, wiele więcej. Efektowne podsumowanie Twojego
                        profilu z podziałem na miesiące i lata.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="mainpage4"><h2>Film - pamiętniki developerskie</h2></section>
    <!--<section id="mainpage5"><h2>Fifth</h2></section>-->
</div>

<div id="slide-nav">
    <ul>
        <li class="active"><a href="#mainpage1"></a></li>
        <li><a href="#mainpage2"></a></li>
        <li><a href="#mainpage3"></a></li>
        <li><a href="#mainpage4"></a></li>
        <!--<li><a href="#mainpage5"></a></li>-->
    </ul>
</div>