<div class="row">
    <div class="span6">
        <div class="widget widget-table action-table">
            <div class="widget-header"> <i class="icon-th-list"></i>
                <h3>Zmień hasło</h3>
            </div>

            <!-- /widget-header -->
            <div class="widget-content" style="padding: 20px;">
                <?php
                    if($resp['type'] === 0){
                        echo '<div class="alert alert-danger">'.$resp['text'].'</div>';
                    }
                    elseif($resp['type'] === 1){
                        echo '<div class="alert alert-success">'.$resp['text'].'</div>';
                    }
                ?>

                <form action="main/changepassword/" method="post">
                    <input type="hidden" name="csrf_token" value="<?php echo $this->NoCSRFToken;?>" />
                    <div class="settings-item">
                        <label>Stare hasło</label>
                        <input type="password" name="old">
                    </div>

                    <div class="settings-item">
                        <label>Nowe hasło</label>
                        <input type="password" name="password1">
                    </div>
                    <div class="settings-item">
                        <label>Powtórz nowe hasło</label>
                        <input type="password" name="password2">
                    </div>

                    <button class="btn btn-primary" style="float: right">Zapisz</button>
                </form>
            </div>
            <!-- /widget-content -->
        </div>
        <!-- /widget -->
        <!-- /widget -->
    </div>

</div>
<!-- /row -->